/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.twcrone.kt.coroutines

import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() = runBlocking { // this: CoroutineScope
    launch { eet() }
    println("Do") // main coroutine continues while a previous one is delayed
}

suspend fun eet() {
    delay(1000L)
    println("Eeet!!!")
}